### ISSUE TITLE
New version not working?

### ISSUE THREAD

**Issue by reissken** [raspad-tablet/raspad-auto-rotator#2]
I just installed a new SD card with Raspberry PI OS and went through the install of the auto-rotator. It will not recognize it, but it does over-ride if I try to set a manual orientation of the screen.

**Comment by GolonkaMarek** [comment]
I confirm that it is not working at all with new version of raspberry pi os.

**Comment by CleyFaye** [comment]
I also can't get the accelerometer to work.

What I checked:

- I2C is enabled on the raspberry pi
- the device do appear when probing i2c
- additionally I looked into the code of sh3001; everything is in order: in init, the correct value is read from i2c when probing the device, and reading value do not fail/stall. the device just *always* read 0 for acc and gyro

The weird thing is, it did work *once*. Without any intervention; I just started the raspad and it worked fine, so the hardware seems to be able to work. It never happened again though.

I'm more than willing to help debugging this, but I'm very unfamiliar with i2c and have no idea what I should probe, beyond what's already readen/written by the sh3001 lib.

**Comment by HeinzRuetschi** [comment]
Had problem to make it work. Got error with raspad-auto-rotator reset command:

Traceback (most recent call last):
  File "/usr/local/bin/raspad-auto-rotator", line 15, in <module>
    sensor = Sh3001(db=CONFIG_FILE)
  File "/usr/local/lib/python3.9/dist-packages/sh3001-0.0.1-py3.9.egg/sh3001/sh3001.py", line 391, in __init__
    super().__init__()
  File "/usr/local/lib/python3.9/dist-packages/sh3001-0.0.1-py3.9.egg/sh3001/i2c.py", line 12, in __init__
    self._smbus = SMBus(self._bus)
FileNotFoundError: [Errno 2] No such file or directory

After activating the I2C interface in the Raspberry Pi-Configuration the error stopped and the rotation detection worked.

To switch the I2C ON is not mentioned in the code instructions and should be added.
